#!/usr/bin/env python3
"""
Preview script for session event JSON files.

This script reads a session_event.json file generated by Project Ceres and
displays a human-readable preview of what a Discord bot would post.

Usage:
    python preview_session_event.py [path_to_json_file]

If no path is provided, defaults to "exports/session_event.json" relative to
the repository root.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Optional


def load_session_event(json_path: Path) -> dict:
    """
    Load and parse a session event JSON file.
    
    Args:
        json_path: Path to the JSON file
        
    Returns:
        Dictionary containing the session event data
        
    Raises:
        FileNotFoundError: If the JSON file does not exist
        json.JSONDecodeError: If the JSON file is invalid
    """
    if not json_path.exists():
        raise FileNotFoundError(f"JSON file not found: {json_path}")
    
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def format_duration(minutes: int) -> str:
    """
    Format duration in minutes as a human-readable string.
    
    Args:
        minutes: Duration in minutes
        
    Returns:
        Formatted string (e.g., "4 hours", "90 minutes")
    """
    if minutes < 60:
        return f"{minutes} minute{'s' if minutes != 1 else ''}"
    
    hours = minutes // 60
    remaining_minutes = minutes % 60
    
    if remaining_minutes == 0:
        return f"{hours} hour{'s' if hours != 1 else ''}"
    else:
        return f"{hours} hour{'s' if hours != 1 else ''} {remaining_minutes} minute{'s' if remaining_minutes != 1 else ''}"


def check_ics_file_exists(ics_path_str: str) -> tuple[bool, Path]:
    """
    Check if the ICS file exists at the specified path.
    
    Args:
        ics_path_str: Path to the ICS file (absolute or relative)
        
    Returns:
        Tuple of (exists: bool, resolved_path: Path)
    """
    ics_path = Path(ics_path_str)
    
    # If relative path, try resolving from repo root
    if not ics_path.is_absolute():
        # Try to find repo root (look for assistant.py or pantheon/)
        script_dir = Path(__file__).parent
        repo_root = script_dir.parent.parent
        
        # Try relative to repo root
        candidate = repo_root / ics_path
        if candidate.exists():
            return (True, candidate.resolve())
        
        # Try relative to script location
        candidate = script_dir / ics_path
        if candidate.exists():
            return (True, candidate.resolve())
    
    # Try absolute path or relative to current working directory
    if ics_path.exists():
        return (True, ics_path.resolve())
    
    return (False, ics_path)


def preview_session_event(data: dict) -> None:
    """
    Print a human-readable preview of the session event.
    
    Args:
        data: Dictionary containing session event data
    """
    title = data.get("title", "(No title)")
    description = data.get("description")
    start_iso = data.get("start_iso", "(Unknown)")
    end_iso = data.get("end_iso")
    duration_minutes = data.get("duration_minutes", 0)
    timezone = data.get("timezone", "(Unknown)")
    ics_path_str = data.get("ics_path", "")
    message_text = data.get("message_text", "(No message text)")
    google_calendar_url = data.get("google_calendar_url")
    
    # Check if ICS file exists
    ics_exists, ics_resolved = check_ics_file_exists(ics_path_str)
    
    # Format duration
    duration_str = format_duration(duration_minutes)
    
    # Print preview
    print("=" * 60)
    print("Session Event Preview (for Discord)")
    print("=" * 60)
    print(f"\nTitle:        {title}")
    print(f"When:         {start_iso} (timezone: {timezone})")
    if end_iso:
        print(f"Ends:         {end_iso}")
    print(f"Duration:     {duration_str} ({duration_minutes} minutes)")
    print(f"\nICS File:     {ics_resolved}")
    print(f"              [exists: {ics_exists}]")
    
    if description:
        print(f"\nDescription:")
        print(f"  {description}")
    
    if google_calendar_url:
        print(f"\nGoogle Calendar URL:")
        print(f"  {google_calendar_url}")
    else:
        print(f"\nGoogle Calendar URL: None")
    
    print(f"\nMessage Text:")
    print("-" * 60)
    print(message_text)
    print("-" * 60)
    print()


def main() -> int:
    """
    Main entry point for the preview script.
    
    Returns:
        Exit code (0 for success, 1 for error)
    """
    parser = argparse.ArgumentParser(
        description="Preview a session event JSON file for Discord posting"
    )
    parser.add_argument(
        "json_path",
        nargs="?",
        default="exports/session_event.json",
        help="Path to the session event JSON file (default: exports/session_event.json)"
    )
    
    args = parser.parse_args()
    
    # Resolve JSON path
    json_path = Path(args.json_path)
    
    # If relative, try resolving from repo root
    if not json_path.is_absolute():
        script_dir = Path(__file__).parent
        repo_root = script_dir.parent.parent
        candidate = repo_root / json_path
        if candidate.exists():
            json_path = candidate
        else:
            # Try relative to current working directory
            json_path = Path(args.json_path)
    
    try:
        data = load_session_event(json_path)
        preview_session_event(data)
        return 0
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        print(f"\nHint: Make sure you've run 'session-discord-export' first to generate the JSON file.", file=sys.stderr)
        return 1
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON file: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Error: Unexpected error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())

